### ISSUE TITLE
No 3D NDT map?

### ISSUE THREAD

**Issue by RENyunfan** [cogsys-tuebingen/cslibs_mapping#5]
Hi,

Thanks for your opensource. I'm quite interested in building a 3d-NDT map. But when I launched the example, the 3D-NDT in rviz didn't show any things. Is there anything wrong?
Everything is showing except the 3D-NDT map.

**Comment by ZikeYan** [comment]
> Hi,
> 
> Thanks for your opensource. I'm quite interested in building a 3d-NDT map. But when I launched the example, the 3D-NDT in rviz didn't show any things. Is there anything wrong?
> Everything is showing except the 3D-NDT map.

Hi,

Did you solve this issue? I met the problem as well. Everything is showing except the NDT map.

**Comment by c-schulz** [comment]
Hi,

I suppose this is because of a static transformation being published only at the beginning of the bag file. Can you try launching rviz separately? Please try the following:
1. uncomment the rviz node in the example launch file
2. launch the example launch file
3. start rviz and open the example config file (in a separate terminal)
4. then start the bag file by pressing the space bar in the terminal where you started the launch file

Please also note that the visualization of the 3D NDT map is not very detailed and that the performance of the ONDT map can be tuned with some parameters.

**Comment by c-schulz** [comment]
I might have found another reason: please build with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` or `-DCMAKE_BUILD_TYPE=Release`.
